Add ansible inventory generation
Zenika/train pull request #1
Opened 2019-02-13 23:37 UTC by pyaillet

The goal of this PR is to be able to generate an ansible inventory from various tags.
Example:

```
[pyaillet] # <= User tag
63.32.44.140 tagged=yes private_ip=10.0.7.158 dns_name=ec2-63-32-44-140.eu-west-1.compute.amazonaws.com ansible_ssh_private_key_file=/host/20190213-kubeadmin/users/pyaillet/pyaillet-20190213-kubeadmin.pem

[kubeadm-1] # <= Lab tag
63.32.44.140 tagged=yes private_ip=10.0.7.158 dns_name=ec2-63-32-44-140.eu-west-1.compute.amazonaws.com ansible_ssh_private_key_file=/host/20190213-kubeadmin/users/pyaillet/pyaillet-20190213-kubeadmin.pem

[node-0] # <= node name extracted from the instance name which is: "<user>-<tag>-<count>"
63.32.44.140 tagged=yes private_ip=10.0.7.158 dns_name=ec2-63-32-44-140.eu-west-1.compute.amazonaws.com ansible_ssh_private_key_file=/host/20190213-kubeadmin/users/pyaillet/pyaillet-20190213-kubeadmin.pem
```

2019-02-14 06:00 UTC, pyaillet commented
Also add ssh_config:

```

Host node-0
     HostName 63.32.44.140
     User ubuntu
     IdentityFile /host/20190213-kubeadmin/users/pyaillet/pyaillet-20190213-kubeadmin.pem
```

2019-02-15 09:43 UTC, zigarn requested changes
Erreurs PEP8 (exécution de `pycodestyle`)

2019-02-15 09:43 UTC, zigarn commented on train/train.py
> +parser.add_argument('-n',
train/train.py:54:26: W291 trailing whitespace

2019-02-15 09:43 UTC, zigarn commented on train/vpc/labs.py
> +    if not 'Name' in instance.tags.keys():
train/vpc/labs.py:141:8: E713 test for membership should be 'not in'

2019-02-15 09:43 UTC, zigarn commented on train/vpc/labs.py
> +                                                            user)
train/vpc/labs.py:152:66: W291 trailing whitespace

2019-02-15 09:43 UTC, zigarn commented on train/vpc/labs.py
> +def ssh_config(conn, user_vpc, user):
train/vpc/labs.py:154:1: E302 expected 2 blank lines, found 1

2019-02-15 09:43 UTC, zigarn commented on train/vpc/labs.py
> +    reservations = conn.get_all_instances(filters = {'vpc-id': user_vpc.id,
train/vpc/labs.py:156:50: E251 unexpected spaces around keyword / parameter equals

2019-02-15 09:43 UTC, zigarn commented on train/vpc/labs.py
> +def instance_to_inventory(instance):
train/vpc/labs.py:162:1: E302 expected 2 blank lines, found 1

2019-02-15 09:43 UTC, zigarn commented on train/vpc/labs.py
> +                                           instance.private_ip_address,
train/vpc/labs.py:166:44: E128 continuation line under-indented for visual indent
train/vpc/labs.py:167:44: E128 continuation line under-indented for visual indent
train/vpc/labs.py:168:44: E128 continuation line under-indented for visual indent
train/vpc/labs.py:169:44: E128 continuation line under-indented for visual indent

2019-02-15 09:43 UTC, zigarn commented on train/vpc/labs.py
> +def add_to_dict(instance, aux, tag):
train/vpc/labs.py:173:1: E302 expected 2 blank lines, found 1

2019-02-15 09:43 UTC, zigarn commented on train/vpc/labs.py
> +    if not tag in instance.tags.keys():
train/vpc/labs.py:174:8: E713 test for membership should be 'not in'

2019-02-15 09:43 UTC, zigarn commented on train/vpc/labs.py
> +def add_node_to_instance(instance):
train/vpc/labs.py:180:1: E302 expected 2 blank lines, found 1

2019-02-15 09:43 UTC, zigarn commented on train/vpc/labs.py
> +    if not 'Name' in instance.tags.keys():
train/vpc/labs.py:181:8: E713 test for membership should be 'not in'

2019-02-15 09:43 UTC, zigarn commented on train/vpc/labs.py
> +def inventory(conn, user_vpc):
train/vpc/labs.py:187:1: E302 expected 2 blank lines, found 1

2019-02-15 09:43 UTC, zigarn commented on train/vpc/labs.py
> +    reservations = conn.get_all_instances(filters = {'vpc-id': user_vpc.id})
train/vpc/labs.py:191:50: E251 unexpected spaces around keyword / parameter equals

2019-02-15 09:43 UTC, zigarn commented on train/vpc/labs.py
> +
train/vpc/labs.py:205:1: E302 expected 2 blank lines, found 1

2019-02-15 14:45 UTC, zigarn requested changes

2019-02-15 14:45 UTC, zigarn commented on train/vpc/labs.py
> +    return """
Serait plus lisible avec le template dans une variable puis le `format` sur ce template je pense

2019-02-15 14:45 UTC, zigarn commented on train/vpc/labs.py
> +        return "{0} tagged=yes private_ip={1} dns_name={2} \
Serait plus lisible avec le template dans une variable puis le `format` sur ce template je pense

2019-02-15 14:45 UTC, zigarn commented on train/vpc/labs.py
> +    if not instance.tags[tag] in aux.keys():
A priori, pas besoin du `.keys()`

2019-02-15 14:45 UTC, zigarn commented on train/vpc/labs.py
> +    aux[instance.tags[tag]] += instance_to_inventory(instance)
Ou sinon ça pour les 3 précédentes lignes :

```python
aux[instance.tags[tag]] = aux.get(instance.tags[tag], "") + instance_to_inventory(instance)
```

2019-02-18 09:34 UTC, pyaillet commented on train/vpc/labs.py
> +    return """
👍
Je l'ai fait pour d'autres également

2019-02-18 09:34 UTC, pyaillet commented on train/vpc/labs.py
> +        return "{0} tagged=yes private_ip={1} dns_name={2} \
👍

2019-02-18 09:45 UTC, pyaillet commented
Thanks for the review, I made some fixes !

2019-04-13 08:22 UTC, zigarn approved these changes

2019-04-13 09:23 UTC, merged